name: PKGBUILD

on: [push, pull_request]

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: makepkg
        run: |
          docker run --interactive --tty --rm --volume .:/package faddat/makepkg

